### PR TITLE
fix: QS tile related issues

### LINKED ISSUE #280: app launches when trying to start screen recording via quick settings toggle
### Steps to reproduce

1. setup the app
2. add quick settings toggle for screen recording 
3. start recording 

### Expected behavior

a popup should ask for start screen recording 

### Actual behavior

the app lanches and then asks for start screen recording 

### Record You version

7.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SuhasDissa**
fix #280

This PR also makes it possible to start a screen recording/audio recording when the app is in the foreground.

### CODE REVIEW

**Comment by Bnyro** [comment]
Maybe we could show a dialog asking for the permissions with some information about why it's needed for the quick tiles and that they won't work otherwise? (Of course granting the permissions must stay optional, but we can at least tell users that they're needed before they run into issues)

**Comment by SuhasDissa** [comment]
Now the overlay permission will be granted automatically

**Comment by Bnyro** [comment]
I think we still need to request the display over other apps permission manually on Android 11 and above?

**Comment by SuhasDissa** [comment]
> I think we still need to request the display over other apps permission manually on Android 11 and above?
> 
> How's that supposed to work without them?

`android.permission.SYSTEM_ALERT_WINDOW` will automatically be granted when running [`getMediaProjection()`](https://developer.android.com/reference/kotlin/android/media/projection/MediaProjectionManager#getmediaprojection)

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
